schema_version: 1

context:
  name: peak-finder-app
  version: 0.3.0a1
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{python_min}}.*
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    # Mira packages
    - curve-apps >=0.3.0a, <0.4.dev
    - geoapps-utils >=0.6.0a, <0.7.dev
    - geoh5py >=0.12.0a, <0.13.dev
    # direct dependencies
    - dask-core >=2025.3,<2025.4.dev
    - distributed >=2025.3,<2025.4.dev
    - h5py >=3.2.1, <4.0.dev
    - numpy >=1.26.0, <1.27.dev
    - pillow >=10.3.0, <10.4.dev
    - plotly >=5.19.0, <5.20.dev
    - pydantic >=2.5.2, <3.0.dev
    - scikit-image >=0.24.0, <0.25.dev
    - scipy >=1.14.0, <1.15.dev
    - tqdm >=4.66.1, <5.0.dev
  run_constraints:
    - dash >=2.12.0,<3.0.dev
    - dash-daq >=0.5.0,<0.6.dev
    - flask >=3.0.3,<4.0.dev
    - pyqtwebengine >=5.15.9,<5.16.dev
    - pyside2 >=5.15.15,<5.16.dev

tests:
  - python:
      imports:
        - peak_finder
        - geoh5py
        - dask
        - distributed

      # `pip check` fails on missing dask-core because it only sees name 'dask'
      # Possibly, use custom mapping for dask => dask-core
      # See `conda-lock --pypi_to_conda_lookup_file`, or the `pixi` option "conda-pypi-map"
      pip_check: false
  - script:
      - pytest --ignore=tests/version_test.py
      - pip list
    requirements:
      run:
        - pip
        - pytest
        - dash >=2.12.0,<3.0.dev
        - dash-daq >=0.5.0,<0.6.dev
        - flask >=3.0.3,<4.0.dev
        - pyqtwebengine >=5.15.9,<5.16.dev
        - pyside2 >=5.15.15,<5.16.dev
    files:
      source:
        - tests/

about:
  summary: Peak Finder App
  description: |
    Peak-finder-app is a package for the detection and grouping of time-domain electromagnetic
    (TEM) anomalies measured along flight lines.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/peak-finder-app
  documentation: https://mirageoscience-peak-finder-app.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
